export default [
  {
    _id: '1',
    sub: '31',
    email: 'eric@gmail.com',
    given_name: 'Eric',
    name: 'Eric Kuehnemann',
    picture: 'https://source.unsplash.com/1600x900/?guitar',
    events: {
      eventIds: ['6', '8', '9'],
      ref: 'Event',
    },
    clout: 50,
    awards: ['vegetarian master', 'sides ninja'],
    foods: [{}],
  },
  {
    _id: '2',
    sub: '32',
    email: 'adonis@gmail.com',
    given_name: 'Adonis',
    name: 'Adonis Suriel',
    picture: 'https://source.unsplash.com/1600x900/?guitar',
    events: {
      eventIds: ['6', '7', '9'],
      ref: 'Event',
    },
    clout: 100,
    awards: ['meat master', 'mains maniac'],
    foods: [{}],
  },
  {
    _id: '3',
    sub: '33',
    email: 'fede@gmail.com',
    given_name: 'Fede',
    name: 'Federico Jimenez',
    picture: 'https://source.unsplash.com/1600x900/?guitar',
    events: {
      eventIds: ['6', '7', '8'],
      ref: 'Event',
    },
    clout: 250,
    awards: ['world traveler', 'sides ninja'],
    foods: [{}],
  },
  {
    sub: '34',
    _id: '4',
    email: 'john@gmail.com',
    given_name: 'John',
    name: 'John Hollister',
    picture: 'https://source.unsplash.com/1600x900/?guitar',
    events: {
      eventIds: ['6', '7', '8', '9'],
      ref: 'Event',
    },
    clout: 50,
    awards: ['meat master', 'mains maniac'],
    foods: [{}],
  },
  {
    sub: '35',
    _id: '5',
    email: 'caity@gmail.com',
    given_name: 'Caity',
    name: 'Caity Opelka',
    picture: 'https://source.unsplash.com/1600x900/?guitar',
    events: {
      eventIds: ['7', '8', '9'],
      ref: 'Event',
    },
    clout: 50,
    awards: ['vegetarian master', 'sides ninja'],
    foods: [{}],
  },
];
